### ISSUE TITLE
How to add time-stamp in config file?

### ISSUE THREAD

**Issue by laichiaheng** [Duncaen/OpenDoas#51]
Do I just add `--time-stamp` in it?
Should I add s or m behind the number? Such as 10 seconds and 2 minutes.

**Comment by Duncaen** [comment]
If the question is how to change the time of validity, this is currently not configurable and fixed at 5 minutes.

**Comment by rsramkis** [comment]
> If the question is how to change the time of validity, this is currently not configurable and fixed at 5 minutes.

I was reviewing this ticket and I'm still not sure what format to follow to add the "--with-timestamp" to the /etc/doas.conf configuration file. Would the correct configuration line to add time-stamp be:

`permit test_user --with-timestamp as root`

**Comment by Duncaen** [comment]
`--with-timestamp` is the option for the configure script `./configure --with-timestamp`.

If opendoas is build with that then you can use the `persist` option with your doas rules `permit persist test_user as root`.

**Comment by rsramkis** [comment]
> `--with-timestamp` is the option for the configure script `./configure --with-timestamp` to build opendoas with support for timestamp files for the `persist` option.
> 
> If opendoas is build with that then you can use the `persist` option with your doas rules `permit persist test_user as root`.

Perfect. If I decide to use this option I will do as you say and update the build packge configuration file and then compile opendoas. Thank you for your help.
